CREATE TABLE Players (
    PlayerID INTEGER NOT NULL PRIMARY KEY,
    RoomId INTEGER,
    Name VARCHAR(30) NOT NULL UNIQUE,
    Health INTEGER NOT NULL,
    Damage INTEGER NOT NULL,
    ExpPoints INTEGER NOT NULL,
    Level INTEGER NOT NULL,
    FOREIGN KEY (RoomId) REFERENCES Rooms (RoomId) ON UPDATE CASCADE
);

CREATE TABLE Rooms (
    RoomId INTEGER NOT NULL PRIMARY KEY,
    Name VARCHAR(30) NOT NULL UNIQUE,
    Level INTEGER NOT NULL
);

CREATE TABLE EnemiesInTheRooms (
    RoomId INTEGER NOT NULL,
    EnemyId INTEGER NOT NULL,
    FOREIGN KEY (RoomId) REFERENCES Rooms (RoomId) ON UPDATE CASCADE,
    FOREIGN KEY (EnemyId) REFERENCES Enemies (EnemyId) ON UPDATE CASCADE
);

CREATE TABLE Enemies (
    EnemyId INTEGER NOT NULL PRIMARY KEY,
    ItemId INTEGER,
    Type VARCHAR(30) NOT NULL,
    Health INTEGER NOT NULL,
    Damage INTEGER NOT NULL,
    Level INTEGER NOT NULL,
    FOREIGN KEY (ItemId) REFERENCES Items (ItemId) ON UPDATE CASCADE    
);

CREATE TABLE Inventory (
    PlayerID INTEGER NOT NULL,
    WeaponSlot INTEGER,
    ArmorSlot INTEGER,
    FOREIGN KEY (WeaponSlot) REFERENCES Items (WeaponSlot) ON UPDATE CASCADE,
    FOREIGN KEY (ArmorSlot) REFERENCES Items (ArmorSlot) ON UPDATE CASCADE,
    FOREIGN KEY (PlayerID) REFERENCES Players (PlayerID) ON UPDATE CASCADE
);

CREATE TABLE Items (
    ItemId INTEGER NOT NULL PRIMARY KEY,
    ItemType VARCHAR(30) NOT NULL,
    Health INTEGER,
    Damage INTEGER,
    Level INTEGER NOT NULL
);
